export interface Scene {
  id: number;
  prompt: string;      // Input from Box 1
  script: string;      // Input from Box 2
  imageUrl?: string;   // Generated by Gemini
  status: 'pending' | 'generating_image' | 'ready' | 'error';
  startTime: number;   // Timestamp in seconds for when this scene appears
}

export interface ProjectData {
  scenes: Scene[];
  audioBuffer: AudioBuffer | null;
  duration: number;
}

export enum PlaybackState {
  IDLE = 'IDLE',
  PLAYING = 'PLAYING',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED'
}
